### ISSUE TITLE
go test ./... fails

### ISSUE THREAD

**Issue by xcthulhu** [ethereum/ethash#7]
When I try to run tests, I get the following failure

```
$ go test ./...
?   	github.com/ethereum/ethash	[no test files]
2015/03/16 11:30:22 Block Number:  5
2015/03/16 11:30:22 difficulty 10000
--- FAIL: TestEthash (1.75s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4175c72]

goroutine 6 [running]:
testing.func·006()
	/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:441 +0x181
github.com/ethereum/ethash.(*Ethash).UpdateDAG(0xc208030460)
	/Users/mpwd/.go/src/github.com/ethereum/ethash/ethash.go:172 +0x5b2
github.com/ethereum/ethash.(*Ethash).FullHash(0xc208030460, 0x0, 0xc2080bf120, 0x20, 0x20, 0x0, 0x0, 0x0)
	/Users/mpwd/.go/src/github.com/ethereum/ethash/ethash.go:388 +0x4c
github.com/ethereum/ethash/test/go.TestEthash(0xc20807e090)
	/Users/mpwd/.go/src/github.com/ethereum/ethash/test/go/ethash_test.go:46 +0x5cd
testing.tRunner(0xc20807e090, 0x46db620)
	/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:447 +0xbf
created by testing.RunTests
	/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:555 +0xa8b

goroutine 1 [chan receive]:
testing.RunTests(0x45c3050, 0x46db620, 0x2, 0x2, 0xc20809e401)
	/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:556 +0xad6
testing.(*M).Run(0xc208030ff0, 0x4705fa0)
	/usr/local/Cellar/go/1.4.2/libexec/src/testing/testing.go:485 +0x6c
main.main()
	github.com/ethereum/ethash/test/go/_test/_testmain.go:54 +0x1d5

goroutine 5 [select]:
github.com/ethereum/go-ethereum/logger.dispatchLoop()
	/Users/mpwd/.go/src/github.com/ethereum/go-ethereum/logger/sys.go:41 +0x6d0
created by github.com/ethereum/go-ethereum/logger.init·1
	/Users/mpwd/.go/src/github.com/ethereum/go-ethereum/logger/sys.go:20 +0x25

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.4.2/libexec/src/runtime/asm_amd64.s:2232 +0x1
FAIL	github.com/ethereum/ethash/test/go	1.933s
```

**Comment by xcthulhu** [comment]
Upstream `go-ethereum` needs to stabilize before this issue can be tackled.

It should be noted that many of the changes to this repo break the `ethash.go`.
